version: '3'
services:
    web:
        image: nginx:latest
        container_name: yii2-web
        restart: always
        sysctls:
            net.core.somaxconn: "65535"
            net.ipv4.tcp_syncookies: 0
        ulimits:
            nproc: 65535
            nofile:
                soft: 20000
                hard: 40000
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/ssl:/etc/ssl"
            - "./web:/var/www/html"
        ports:
            - "8000:80"
            - "3001:443"
        networks:
            - yii2net
        depends_on:
            - php
            - mysqldb
    php:
        image: php:fpm-bookworm
        container_name: yii2-app
        restart: always
        sysctls:
            net.core.somaxconn: "65535"
            net.ipv4.tcp_syncookies: 0
        ulimits:
            nproc: 65535
            nofile:
                soft: 20000
                hard: 40000
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./web:/var/www/html"
        working_dir: /var/www/html
        environment:
            YII_ENV: dev
        networks:
            - yii2net
    composer:
        image: "composer"
        container_name: yii2-composer
        volumes:
            - "./web:/app"
        command: install
    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: yii2-pma
        sysctls:
            net.core.somaxconn: "65535"
            net.ipv4.tcp_syncookies: 0
        ulimits:
            nproc: 65535
            nofile:
                soft: 20000
                hard: 40000
        ports:
            - "8091:80"
        networks:
            - yii2net
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=${MYSQL_HOST}
        restart: always
        depends_on:
            - mysqldb
    mysqldb:
        image: mysql:8.3.0
        container_name: ${MYSQL_HOST}
        sysctls:
            net.core.somaxconn: "65535"
            net.ipv4.tcp_syncookies: 0
        ulimits:
            nproc: 65535
            nofile:
                soft: 20000
                hard: 40000
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        command: mysqld --sql_mode=""
        volumes:
            - "./data/db/mysql:/var/lib/mysql"
        ports:
            - "8989:3306"
        networks:
            - yii2net
    redis:
        image: redis:7.2.4-alpine3.19
        container_name: yii2-redis
        sysctls:
            net.core.somaxconn: "65535"
            net.ipv4.tcp_syncookies: 0
        ulimits:
            nproc: 65535
            nofile:
                soft: 20000
                hard: 40000
        restart: always
        volumes:
            - ./data/redis:/usr/local/etc/redis
        ports:
            - "6379:6379"
        networks:
            - yii2net
        command: 'redis-server /usr/local/etc/redis/redis.conf'

networks:
  yii2net:
    driver: bridge